### ISSUE TITLE
에러가 엄청나게 찍힘

### ISSUE THREAD

**Issue by jwvg0425** [jwvg0425/algorithm#10]
배포된 페이지 들어가서 콘솔창 보면 이상한 에러가 엄청나게 찍히는데 원인이 무엇일까

**Comment by joonas-yoon** [comment]
스크롤을 움직일때마다 아래 오류가 엄청나게 찍히는 걸 말씀하시는 게 맞죠?

```
[theme.js:4] Uncaught TypeError: Cannot read property 'split' of undefined
```

이와 관련한 GitBook의 이슈입니다. (아직 open 상태네요.)
https://github.com/GitbookIO/gitbook/issues/1525

**Comment by jwvg0425** [comment]
아하.. 일단 놔둬야겠네요 ㅠㅠ 감사합니다.
