### ISSUE TITLE
wiki 문서 추가

### ISSUE THREAD

**Issue by joonas-yoon** [jwvg0425/algorithm#9]
gitbook을 로컬에서 설치하는 방법을 작성하고 싶습니다.

**Comment by jwvg0425** [comment]
이 repo 위키에 추가하고 싶다는 말씀이시죠? 위키는 아마 아무나 편집 가능할텐데.. 제가 문서를 만들어야 편집이 되던가요? 일단 문서는 만들어두겠습니다!

**Comment by joonas-yoon** [comment]
음.. 저도 아무나 편집 가능할 줄 알았는데, 별도의 권한 설정이 필요한가보네요. 

https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by jwvg0425** [comment]
앗 그렇네요. 예전엔 그냥 다 됐었는데 권한 설정이 추가됐나봐요. 설정 풀었으니 편집 가능할거에요!
